name: someone_datingapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  zego_uikit_prebuilt_call: ^4.8.4

  iconsax: ^0.0.8
  logger: ^2.0.1
  google_fonts: ^5.0.0
  go_router: ^10.1.0
  ionicons: ^0.1.2
  flutter_svg: ^2.0.4
  step_progress_indicator: ^1.0.2
  transparent_image: ^2.0.0
  get: ^4.6.5
  get_storage: ^2.1.1
  rxdart: ^0.27.7
  http: ^1.2.1
  intl: ^0.18.1
  url_launcher: ^6.2.5
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  image_picker: ^1.1.0
  cached_network_image: ^3.3.1
  liquid_pull_to_refresh: ^3.0.1
  firebase_core: ^2.27.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.10
  firebase_auth: ^4.18.0
  firebase_messaging: ^14.8.1
  firebase_storage: ^11.7.1
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/jpg/
    - assets/images/png/
    - assets/images/svg/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/lottie/
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/lottie/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
