// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPbiJNTSTHGaVeGaj-QaixAjbRQwIMmUo',
    appId: '1:280465158374:web:40178c0b5b937f90660b27',
    messagingSenderId: '280465158374',
    projectId: 'someone-datingapp',
    authDomain: 'someone-datingapp.firebaseapp.com',
    storageBucket: 'someone-datingapp.appspot.com',
    measurementId: 'G-QGQEDQSQNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhuU2hOePaq8FpjjWV0LNBB3ISZx4jl6M',
    appId: '1:280465158374:android:615e52f01ff9ee60660b27',
    messagingSenderId: '280465158374',
    projectId: 'someone-datingapp',
    storageBucket: 'someone-datingapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrodWky1ejgECt9Ta3DmtZeia5yU6xc1w',
    appId: '1:280465158374:ios:af56b8d724b799f0660b27',
    messagingSenderId: '280465158374',
    projectId: 'someone-datingapp',
    storageBucket: 'someone-datingapp.appspot.com',
    androidClientId:
        '280465158374-abblgbo39q5edk46dqbg3ng03l7d2kgj.apps.googleusercontent.com',
    iosClientId:
        '280465158374-3gbd01pqq7u1coqbfmjomcavhtecl15f.apps.googleusercontent.com',
    iosBundleId: 'com.example.someoneDatingapp',
  );
}
